name: Upload DAGs to GCS

on:
  push:
    branches:
     # - main Uncomment this code to run the actions

jobs:
  build:
    name: Build and Upload DAGs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Google Cloud SDK
      run: |
        sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates gnupg
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        sudo apt-get install -y gnupg
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
        sudo apt-get update && sudo apt-get install -y google-cloud-sdk

    - name: Authenticate to GCP
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      run: |
        echo "$GCP_SA_KEY" > "${HOME}/gcp-key.json"
        gcloud auth activate-service-account --key-file="${HOME}/gcp-key.json"
        gcloud config set project your-project-id

    - name: Upload DAGs folder to GCS
      run: |
        gsutil -m cp -r dags/* gs://us-central1-mlops-composer-c43be234-bucket/dags/dags/
